apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hr1t2o3bz-java-quarkus
  janus-idp.io/tekton: hr1t2o3bz-java-quarkus
  backstage.io/kubernetes-id: hr1t2o3bz-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hr1t2o3bz-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
